spring:
  application:
    name: springdatajpa

  datasource:
    url: jdbc:postgresql://localhost:5436/springdatajpa
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect